#!/bin/bash

# create all optum1 pairs in one go

absent=$@

printf "optum1amiga:"
python3 pairs.py -g optum1amiga $absent

printf "\noptum1lynx:"
python3 pairs.py -g optum1lynx $absent

python3 pairs.py -u optum1 optum1amiga optum1lynx

printf "\noptum1"
python3 pairs.py -g optum1 $absent
